// <auto-generated />
namespace M4MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Telephone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Telephone));
        
        string IMigrationMetadata.Id
        {
            get { return "202103220137367_Telephone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
